### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'state' of null

### ISSUE THREAD

**Issue by wwolkers** [korylprince/hassio-node-red#12] opened 2018-04-22 22:00 UTC
After running stable for a while, my node-red addon is now crashing regularly with the following error in the logs:

starting version 3.2.4
SSL Disabled
Admin Authentication Enabled
HTTP Authentication Disabled
Current palette version 0.3.0 matches requested version
waiting: waiting for hassio:80 without a timeout
waiting: hassio:80 is available after 0 seconds
waiting: waiting for homeassistant:8123 without a timeout
waiting: homeassistant:8123 is available after 0 seconds
21 Apr 09:06:37 - [info] 

Welcome to Node-RED
===================

21 Apr 09:06:37 - [info] Node-RED version: v0.18.4
21 Apr 09:06:37 - [info] Node.js  version: v8.9.3
21 Apr 09:06:37 - [info] Linux 4.13.0-38-generic x64 LE
21 Apr 09:06:37 - [info] Loading palette nodes
21 Apr 09:06:38 - [warn] ------------------------------------------------------
21 Apr 09:06:38 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
21 Apr 09:06:38 - [warn] ------------------------------------------------------
21 Apr 09:06:38 - [info] Settings file  : /share/node-red/settings.js
21 Apr 09:06:38 - [info] User directory : /share/node-red
21 Apr 09:06:38 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
21 Apr 09:06:38 - [info] Flows file     : /share/node-red/flows.json
21 Apr 09:06:38 - [info] Server now running at http://127.0.0.1:1880/
21 Apr 09:06:38 - [info] Starting flows
21 Apr 09:06:38 - [info] Started flows
21 Apr 09:06:38 - [info] [mqtt-broker:server] Connected to broker: mqtt://192.168.16.5:1883
21 Apr 09:07:34 - [info] Stopping flows
21 Apr 09:07:34 - [info] [mqtt-broker:server] Disconnected from broker: mqtt://192.168.16.5:1883
21 Apr 09:07:34 - [info] Stopped flows
21 Apr 09:07:34 - [info] Starting flows
21 Apr 09:07:34 - [info] Started flows
21 Apr 09:07:34 - [info] [mqtt-broker:server] Connected to broker: mqtt://192.168.16.5:1883
21 Apr 10:31:34 - [warn] [api-current-state:Off Already?] entity could not be found in cache for entity_id: group.livingroom, sending empty payload
22 Apr 00:06:29 - [info] [mqtt-broker:server] Disconnected from broker: mqtt://192.168.16.5:1883
22 Apr 00:06:44 - [info] [mqtt-broker:server] Connected to broker: mqtt://192.168.16.5:1883
22 Apr 10:29:38 - [warn] [api-current-state:Off Already?] entity could not be found in cache for entity_id: group.livingroom, sending empty payload
22 Apr 21:57:30 - [red] Uncaught Exception:
22 Apr 21:57:30 - TypeError: Cannot read property 'state' of null
    at ServerStateChangedNode.onHaEventsStateChanged (/share/node-red/node_modules/node-red-contrib-home-assistant/nodes/server-events-state-changed/server-events-state-changed.js:38:42)
    at emitOne (events.js:121:20)
    at HaEvents.emit (events.js:211:7)
    at HaEvents.onClientMessage (/share/node-red/node_modules/node-home-assistant/lib/ha-events.js:59:22)
    at EventSource.client.on (/share/node-red/node_modules/node-home-assistant/lib/ha-events.js:27:49)
    at emitOne (events.js:116:13)
    at EventSource.emit (events.js:211:7)
    at _emit (/share/node-red/node_modules/eventsource/lib/eventsource.js:222:17)
    at parseEventStreamLine (/share/node-red/node_modules/eventsource/lib/eventsource.js:237:9)
    at IncomingMessage.<anonymous> (/share/node-red/node_modules/eventsource/lib/eventsource.js:200:11)

**Comment by wwolkers** [comment] 2018-04-28 12:15
just as a follow up on my own post, this seems to be a known issue in the node-red-home-assistant:
https://github.com/AYapejian/node-red-contrib-home-assistant/issues/44

**Comment by korylprince** [comment] 2018-05-06 03:03
Duplicate of #11

**Closed as completed by korylprince** 2018-05-06 03:03 UTC
